name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.1-jammy
      options: --user 1001
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4
      
      # Step 2: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Upload Playwright test report as an artifact
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
         name: playwright-report
         path: playwright-report/
         retention-days: 30


